### ISSUE TITLE
save.json edit level 0.1

### ISSUE THREAD

**Issue by Exprescode** [AY1920S1-CS2113T-F14-2/main#233]
![image](https://user-images.githubusercontent.com/13359816/68017358-7f8fb680-fcd1-11e9-90aa-ba60eb078dc7.png)

**Comment by Exprescode** [comment]
![image](https://user-images.githubusercontent.com/13359816/68068423-867cfe80-fd8f-11e9-90ad-87a1829b4046.png)

**Comment by tzw0** [comment]
i think not yet fixed
![image](https://user-images.githubusercontent.com/42692203/68119661-3d1ee180-ff3e-11e9-9c01-b83c06a98b2e.png)

**Comment by Exprescode** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/13359816/68125410-8aa24b00-ff4c-11e9-8571-1a88bc38f387.png)
